/*******************************************************************************
* Copyright (c) 2015 lostinsoftware. All rights reserved.
*
* This library is free software; you can redistribute it and/or modify it under
* the terms of the GNU Lesser General Public License as published by the Free
* Software Foundation; either version 2.1 of the License, or (at your option)
* any later version.
*
* This library is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
* details.
*
* Contributors:
*          lostinsoftware - initial implementation and ongoing maintenance
*          
*******************************************************************************/
package com.lostinsoftware.classicmodels.model;

// Generated 12-ago-2015 22:07:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Offices generated by hbm2java
 */
@Entity
@Table(name = "offices", catalog = "classicmodels")
public class Offices implements java.io.Serializable {

  private String officeCode;
  private String city;
  private String phone;
  private String addressLine1;
  private String addressLine2;
  private String state;
  private String country;
  private String postalCode;
  private String territory;
  private Set<Employees> employeeses = new HashSet<Employees>(0);

  public Offices() {
  }

  public Offices(String officeCode, String city, String phone,
      String addressLine1, String country, String postalCode, String territory) {
    this.officeCode = officeCode;
    this.city = city;
    this.phone = phone;
    this.addressLine1 = addressLine1;
    this.country = country;
    this.postalCode = postalCode;
    this.territory = territory;
  }

  public Offices(String officeCode, String city, String phone,
      String addressLine1, String addressLine2, String state, String country,
      String postalCode, String territory, Set<Employees> employeeses) {
    this.officeCode = officeCode;
    this.city = city;
    this.phone = phone;
    this.addressLine1 = addressLine1;
    this.addressLine2 = addressLine2;
    this.state = state;
    this.country = country;
    this.postalCode = postalCode;
    this.territory = territory;
    this.employeeses = employeeses;
  }

  @Id
  @Column(name = "officeCode", unique = true, nullable = false, length = 10)
  public String getOfficeCode() {
    return this.officeCode;
  }

  public void setOfficeCode(String officeCode) {
    this.officeCode = officeCode;
  }

  @Column(name = "city", nullable = false, length = 50)
  public String getCity() {
    return this.city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  @Column(name = "phone", nullable = false, length = 50)
  public String getPhone() {
    return this.phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  @Column(name = "addressLine1", nullable = false, length = 50)
  public String getAddressLine1() {
    return this.addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  @Column(name = "addressLine2", length = 50)
  public String getAddressLine2() {
    return this.addressLine2;
  }

  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }

  @Column(name = "state", length = 50)
  public String getState() {
    return this.state;
  }

  public void setState(String state) {
    this.state = state;
  }

  @Column(name = "country", nullable = false, length = 50)
  public String getCountry() {
    return this.country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  @Column(name = "postalCode", nullable = false, length = 15)
  public String getPostalCode() {
    return this.postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  @Column(name = "territory", nullable = false, length = 10)
  public String getTerritory() {
    return this.territory;
  }

  public void setTerritory(String territory) {
    this.territory = territory;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "offices")
  public Set<Employees> getEmployeeses() {
    return this.employeeses;
  }

  public void setEmployeeses(Set<Employees> employeeses) {
    this.employeeses = employeeses;
  }

}
