/*******************************************************************************
* Copyright (c) 2015 lostinsoftware. All rights reserved.
*
* This library is free software; you can redistribute it and/or modify it under
* the terms of the GNU Lesser General Public License as published by the Free
* Software Foundation; either version 2.1 of the License, or (at your option)
* any later version.
*
* This library is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
* details.
*
* Contributors:
*          lostinsoftware - initial implementation and ongoing maintenance
*          
*******************************************************************************/
package com.lostinsoftware.classicmodels.model;

// Generated 12-ago-2015 22:07:35 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "classicmodels")
public class Orders implements java.io.Serializable {

  private int orderNumber;
  private Customers customers;
  private Date orderDate;
  private Date requiredDate;
  private Date shippedDate;
  private String status;
  private String comments;
  private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);

  public Orders() {
  }

  public Orders(int orderNumber, Customers customers, Date orderDate,
      Date requiredDate, String status) {
    this.orderNumber = orderNumber;
    this.customers = customers;
    this.orderDate = orderDate;
    this.requiredDate = requiredDate;
    this.status = status;
  }

  public Orders(int orderNumber, Customers customers, Date orderDate,
      Date requiredDate, Date shippedDate, String status, String comments,
      Set<Orderdetails> orderdetailses) {
    this.orderNumber = orderNumber;
    this.customers = customers;
    this.orderDate = orderDate;
    this.requiredDate = requiredDate;
    this.shippedDate = shippedDate;
    this.status = status;
    this.comments = comments;
    this.orderdetailses = orderdetailses;
  }

  @Id
  @Column(name = "orderNumber", unique = true, nullable = false)
  public int getOrderNumber() {
    return this.orderNumber;
  }

  public void setOrderNumber(int orderNumber) {
    this.orderNumber = orderNumber;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "customerNumber", nullable = false)
  public Customers getCustomers() {
    return this.customers;
  }

  public void setCustomers(Customers customers) {
    this.customers = customers;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "orderDate", nullable = false, length = 10)
  public Date getOrderDate() {
    return this.orderDate;
  }

  public void setOrderDate(Date orderDate) {
    this.orderDate = orderDate;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "requiredDate", nullable = false, length = 10)
  public Date getRequiredDate() {
    return this.requiredDate;
  }

  public void setRequiredDate(Date requiredDate) {
    this.requiredDate = requiredDate;
  }

  @Temporal(TemporalType.DATE)
  @Column(name = "shippedDate", length = 10)
  public Date getShippedDate() {
    return this.shippedDate;
  }

  public void setShippedDate(Date shippedDate) {
    this.shippedDate = shippedDate;
  }

  @Column(name = "status", nullable = false, length = 15)
  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  @Column(name = "comments", length = 65535)
  public String getComments() {
    return this.comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  @OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
  public Set<Orderdetails> getOrderdetailses() {
    return this.orderdetailses;
  }

  public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
    this.orderdetailses = orderdetailses;
  }

}
